version: '3.8'

services:
  # FastAPI Backend Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: linkedin-post-generator-api
    ports:
      - "8000:8000"
    environment:
      # Use an empty string for API_KEY if you're handling the key inside the container/code
      - BASE_URL=${BASE_URL:-http://localhost:11434}
      - API_KEY=${API_KEY}
      - MODEL_NAME=${MODEL_NAME:-gpt-4o-mini}
    volumes:
      # Mount .env file for configuration variables
      - ./.env:/app/.env:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - linkedin-app-network

  # Nginx Frontend Service
  frontend:
    image: nginx:alpine
    container_name: linkedin-post-generator-frontend
    ports:
      - "80:80" # Only map HTTP port 80
    volumes:
      # IMPORTANT: Maps local './frontend' folder to Nginx's web root. 
      # index.html MUST be inside your local 'frontend' folder.
      - ./frontend:/usr/share/nginx/html:ro
      # Maps your custom nginx.conf to the Nginx configuration file
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - linkedin-app-network

networks:
  linkedin-app-network:
    driver: bridge
